// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "CITIAPS",
            "url": "https://citiaps.cl",
            "email": "citiaps@usach.cl"
        },
        "license": {
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/encuestaDocenteRespuestas": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Esta funcionalidad recibe un body con los datos del profesor y los puntajes de la encuesta asignados por el alumno, son guardados en la BD y se deja registro de que la encuesta ya fue contestada, además se deja rastro de estos Create.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "EncuestaDocenteRespuestas"
                ],
                "summary": "Guarda las respuestas de una encuesta de un alumno hacia un profesor.",
                "parameters": [
                    {
                        "description": "Datos de la encuesta respondida por el alumno",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EncuestaDocenteRespuestas"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.EncuestaDocenteRespuestas"
                        }
                    },
                    "400": {
                        "description": "Petición erronea",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/encuestaDocenteRespuestas/indexAlumno": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Esta funcionalidad obtiene de la base de datos el año y semestre actual, luego con el codPersona se obtienen los datos del alumno y sus asignaturas, luego con el idCargaTotal, se obtienen los profesores y si las encuestas ya fueron contestadas.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "IndexAlumno"
                ],
                "summary": "Obtiene información del alumno, las asignaturas cursadas en el actual semestre y año, y los profesores de cada asignatura.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IndexAlumno"
                        }
                    },
                    "400": {
                        "description": "Petición erronea",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/encuestaDocenteRespuestas/porContestar": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Esta funcionalidad obtiene de la base de datos el año y semestre actual, luego con el codPersona y el semestre directamente anterior se obtienen las encuestas docentes que faltan por contestar, si se obtiene 1 o más, se retorna un true, en caso contrario un false.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ConfirmacionEncuestasPorContestarRespuestas"
                ],
                "summary": "Obtiene información del alumno, el actual semestre y año actual, y retorna un bool indicando si tiene encuestas docentes por contestar.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.PorContestar"
                        }
                    },
                    "400": {
                        "description": "Petición erronea",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "controller.PorContestar": {
            "type": "object",
            "properties": {
                "porContestar": {
                    "type": "boolean"
                }
            }
        },
        "models.AsistenciaAsign": {
            "type": "object",
            "properties": {
                "´idCargaTotal": {
                    "type": "integer"
                },
                "´porcentaje": {
                    "type": "integer"
                }
            }
        },
        "models.CargaTotalProfesor": {
            "type": "object",
            "properties": {
                "idCargaTotalProfesor": {
                    "type": "integer"
                },
                "nombreCompleto": {
                    "type": "string"
                }
            }
        },
        "models.Contestada": {
            "type": "object",
            "properties": {
                "´flag": {
                    "type": "integer"
                },
                "´idCargaTotal": {
                    "type": "integer"
                }
            }
        },
        "models.EncuestaDocenteRespuestas": {
            "type": "object",
            "properties": {
                "ano": {
                    "type": "integer"
                },
                "comentario": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "idCargaTotalProfesor": {
                    "type": "integer"
                },
                "nota": {
                    "type": "integer"
                },
                "p1": {
                    "type": "integer"
                },
                "p2": {
                    "type": "integer"
                },
                "p3": {
                    "type": "integer"
                },
                "p4": {
                    "type": "integer"
                },
                "p5": {
                    "type": "integer"
                },
                "p6": {
                    "type": "integer"
                },
                "p7": {
                    "type": "integer"
                },
                "p8": {
                    "type": "integer"
                },
                "sem": {
                    "type": "integer"
                }
            }
        },
        "models.IndexAlumno": {
            "type": "object",
            "properties": {
                "anoIngreso": {
                    "type": "integer"
                },
                "anoProcesoNum": {
                    "type": "integer"
                },
                "asignaturasInscritas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SeccionesInscritasAlumno"
                    }
                },
                "asistenciaAsignaturas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AsistenciaAsign"
                    }
                },
                "contestadas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Contestada"
                    }
                },
                "infoPlan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PlanAlumnoActual"
                    }
                },
                "nivelContesta": {
                    "type": "integer"
                },
                "planAlumno": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PlanAlumnoAno"
                    }
                },
                "profesorSeleccionado": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProfesorSeleccionado"
                    }
                },
                "profesores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProfesoresResumen"
                    }
                }
            }
        },
        "models.PlanAlumnoActual": {
            "type": "object",
            "properties": {
                "anoIngreso": {
                    "type": "integer"
                },
                "anoMatricula": {
                    "type": "integer"
                },
                "anoProceso": {
                    "type": "integer"
                },
                "anoplan": {
                    "type": "integer"
                },
                "codCarrera": {
                    "type": "string"
                },
                "codEspecialidad": {
                    "type": "integer"
                },
                "codEstadoFinal": {
                    "type": "integer"
                },
                "codMencion": {
                    "type": "integer"
                },
                "codNivelCarrera": {
                    "type": "integer"
                },
                "codNivelGlobal": {
                    "type": "integer"
                },
                "codTipoMatricula": {
                    "type": "integer"
                },
                "codTipoPlan": {
                    "type": "integer"
                },
                "descripcion": {
                    "type": "string"
                },
                "idMatricula": {
                    "type": "integer"
                },
                "idPlanes": {
                    "type": "integer"
                },
                "nomCarrera": {
                    "type": "string"
                },
                "nomCentro": {
                    "type": "string"
                },
                "nomEspecialidad": {
                    "type": "string"
                },
                "nomMencion": {
                    "type": "string"
                },
                "semEstadoFinal": {
                    "type": "integer"
                }
            }
        },
        "models.PlanAlumnoAno": {
            "type": "object",
            "properties": {
                "anoIngreso": {
                    "type": "integer"
                },
                "anoMatricula": {
                    "type": "integer"
                },
                "anoPrimerIngreso": {
                    "type": "integer"
                },
                "anoProceso": {
                    "type": "integer"
                },
                "anoplan": {
                    "type": "integer"
                },
                "caracteristica": {
                    "type": "string"
                },
                "codEstadoFinal": {
                    "type": "integer"
                },
                "codEstadoRetiro": {
                    "type": "integer"
                },
                "codJornada": {
                    "type": "integer"
                },
                "codModalidad": {
                    "type": "integer"
                },
                "codModoIngreso": {
                    "type": "integer"
                },
                "codNivelCarrera": {
                    "type": "integer"
                },
                "codNivelGlobal": {
                    "type": "integer"
                },
                "codPersona": {
                    "type": "integer"
                },
                "codRegimen": {
                    "type": "integer"
                },
                "codTipoAlumMatr": {
                    "type": "integer"
                },
                "codTipoAlumno": {
                    "type": "integer"
                },
                "codTipoMatricula": {
                    "type": "integer"
                },
                "codTipoPlan": {
                    "type": "integer"
                },
                "codTipoPrueba": {
                    "type": "integer"
                },
                "duracion": {
                    "type": "integer"
                },
                "fechaMatricula": {
                    "type": "string"
                },
                "idCarreraTotal": {
                    "type": "integer"
                },
                "idFichaTesoreria": {
                    "type": "integer"
                },
                "idHojaRuta": {
                    "type": "integer"
                },
                "idMatricula": {
                    "type": "integer"
                },
                "idMatriculaColegio": {
                    "type": "integer"
                },
                "idPlanes": {
                    "type": "integer"
                },
                "idPrueba": {
                    "type": "integer"
                },
                "posicion": {
                    "type": "integer"
                },
                "rutAlum": {
                    "type": "string"
                },
                "semDesvinculacion": {
                    "type": "integer"
                },
                "semEstadoFinal": {
                    "type": "integer"
                },
                "vigencia": {
                    "type": "integer"
                }
            }
        },
        "models.ProfesorSeleccionado": {
            "type": "object",
            "properties": {
                "´idCargaTotal": {
                    "type": "integer"
                },
                "´nombre": {
                    "type": "string"
                }
            }
        },
        "models.ProfesoresResumen": {
            "type": "object",
            "properties": {
                "cargaTotalProfesor": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CargaTotalProfesor"
                    }
                },
                "idCargaTotalProfesor": {
                    "type": "integer"
                }
            }
        },
        "models.SeccionesInscritasAlumno": {
            "type": "object",
            "properties": {
                "HCP": {
                    "type": "number"
                },
                "ambito": {
                    "type": "integer"
                },
                "ano": {
                    "type": "integer"
                },
                "cantidadEstimadaAlum": {
                    "type": "integer"
                },
                "codCategoria": {
                    "type": "integer"
                },
                "codEstadoInscripcion": {
                    "type": "integer"
                },
                "codPersona": {
                    "type": "integer"
                },
                "codTipoSeccion": {
                    "type": "integer"
                },
                "fechaIngreso": {
                    "type": "string"
                },
                "idCargaParcial": {
                    "type": "integer"
                },
                "idCargaTotal": {
                    "type": "integer"
                },
                "idDetalleCategoria": {
                    "type": "integer"
                },
                "idMalla": {
                    "type": "integer"
                },
                "idMallaCd": {
                    "type": "integer"
                },
                "idTipoUsuario": {
                    "type": "integer"
                },
                "idUsuarioAula": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "nomGrupo": {
                    "type": "string"
                },
                "numGrupos": {
                    "type": "integer"
                },
                "opcion": {
                    "type": "integer"
                },
                "sem": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "BearerJWTToken in Authorization Header",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Encuesta docente",
	Description:      "Módulo que incluye el apartado para la selección, desarrollo y envío de una encuesta docente de un alumno a un profesor.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
